name: Build with poetry

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.2
    - name: Install depedencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry  
    - name: Build with poetry
      shell: bash
      run: |
        poetry version $(git tag --points-at HEAD)
        poetry build