# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Package

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/poetry-build
      with:
        python-version: ${{matrix.python-version}}
    - name: Capture artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Python Package
        path: dist/*.whl
    - name: Install wheel
      run: pip install dist/*.whl

  publish-github:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/poetry-build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: dist/*.whl
        token: ${{secrets.GITHUB_TOKEN}}

  publish-pypi:
    needs: [build, publish-github]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/poetry-build
    - name: Publish to pypi
      run: |
        poetry config repositories.pypi https://upload.pypi.org/legacy/
        poetry config pypi-token.pypi ${{secrets.PYPI_API_KEY}}
        poetry publish -r pypi