# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Package

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.2
    - name: Build wheel
      run: |
        echo '${{ github.ref }}'
        pip3 install wheel
        export PIGROMETER_VERSION=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse HEAD | cut -c -7)
        python3 setup.py bdist_egg
    - name: Capture artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Python Package
        path: dist/*.egg

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: Python Package
    - name: Display structure of downloaded files
      run: ls -R
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./*.egg
        token: ${{ secrets.GITHUB_TOKEN }}