# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main", "develop", "feature-github_ci" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
    - name: Capture artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Wheel
        path: dist/*.whl
